platform:
  - x86
  - x64

environment:
  matrix:
    - VSVER: 12
    - VSVER: 10

configuration:
  - --debug
  - shared

matrix:
  allow_failures:
    # not included in AppVeyor right now
    - platform: x64
      VSVER: 10

before_build:
  - ps: >-
      If ($env:Platform -Match "x86") {
        $env:VCVARS_PLATFORM="x86"
        $env:TARGET="VC-WIN32"
        $env:DO="do_ms"
      } Else {
        $env:VCVARS_PLATFORM="amd64"
        $env:TARGET="VC-WIN64A"
        $env:DO="do_win64a"
      }
  - ps: >-
      If ($env:Configuration -Like "*--debug*") {
        $env:TARGET="debug-$env:TARGET"
      }
  - ps: >-
      If ($env:Configuration -Like "*shared*") {
        $env:MAK="ntdll.mak"
      } Else {
        $env:MAK="nt.mak"
      }
  - ps: $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))
  - echo "Using Visual Studio %VSVER%.0 at %VSCOMNTOOLS%"
  - call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" %VCVARS_PLATFORM%
  - perl Configure %TARGET% no-asm
  - call ms\%DO%

build_script:
  - nmake /f ms\%MAK%
